services:
  - type: web
    name: restaurant-ordering
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn resto_project.wsgi
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: resto_project.settings
